model in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperboloidExecutionHierarchicalMuPrecHalf_entrop/hyperboloidExecutionHierarchicalMuPrecHalf_entrop_jags.jags"
data in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperboloidExecutionHierarchicalMuPrecHalf_entrop/hyperboloidExecutionHierarchicalMuPrecHalf_entrop.data"
compile, nchains(1)
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperboloidExecutionHierarchicalMuPrecHalf_entrop/hyperboloidExecutionHierarchicalMuPrecHalf_entrop_7.init"
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperboloidExecutionHierarchicalMuPrecHalf_entrop/hyperboloidExecutionHierarchicalMuPrecHalf_entrop_7.seed"
initialize
update 2000
monitor set kappa, thin(16384)
monitor set tau, thin(16384)
monitor set w, thin(16384)
update 81920000
coda *, stem('samples_7_')
