model in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperbolicExecutionHierarchicalMuPrecHalf_entrop/hyperbolicExecutionHierarchicalMuPrecHalf_entrop_jags.jags"
data in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperbolicExecutionHierarchicalMuPrecHalf_entrop/hyperbolicExecutionHierarchicalMuPrecHalf_entrop.data"
compile, nchains(1)
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperbolicExecutionHierarchicalMuPrecHalf_entrop/hyperbolicExecutionHierarchicalMuPrecHalf_entrop_6.init"
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperbolicExecutionHierarchicalMuPrecHalf_entrop/hyperbolicExecutionHierarchicalMuPrecHalf_entrop_6.seed"
initialize
update 2000
monitor set kappa, thin(8)
monitor set w, thin(8)
update 40000
coda *, stem('samples_6_')
