model in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/unifiedTradeoffExecutionHierarchicalMuPrecHalf_entrop/unifiedTradeoffExecutionHierarchicalMuPrecHalf_entrop_jags.jags"
data in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/unifiedTradeoffExecutionHierarchicalMuPrecHalf_entrop/unifiedTradeoffExecutionHierarchicalMuPrecHalf_entrop.data"
compile, nchains(1)
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/unifiedTradeoffExecutionHierarchicalMuPrecHalf_entrop/unifiedTradeoffExecutionHierarchicalMuPrecHalf_entrop_9.init"
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/unifiedTradeoffExecutionHierarchicalMuPrecHalf_entrop/unifiedTradeoffExecutionHierarchicalMuPrecHalf_entrop_9.seed"
initialize
update 2000
monitor set gamma, thin(64)
monitor set tau, thin(64)
monitor set kappa, thin(64)
monitor set vartheta, thin(64)
monitor set eta, thin(64)
monitor set w, thin(64)
update 320000
coda *, stem('samples_9_')
