model in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperbolicExecutionHierarchicalMuPrecDouble_entrop/hyperbolicExecutionHierarchicalMuPrecDouble_entrop_jags.jags"
data in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperbolicExecutionHierarchicalMuPrecDouble_entrop/hyperbolicExecutionHierarchicalMuPrecDouble_entrop.data"
compile, nchains(1)
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperbolicExecutionHierarchicalMuPrecDouble_entrop/hyperbolicExecutionHierarchicalMuPrecDouble_entrop_3.init"
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/hyperbolicExecutionHierarchicalMuPrecDouble_entrop/hyperbolicExecutionHierarchicalMuPrecDouble_entrop_3.seed"
initialize
update 2000
monitor set kappa, thin(8)
monitor set w, thin(8)
update 40000
coda *, stem('samples_3_')
