%% runAllHierarchicalExecutionModelsStan — fit all hierarchical models via Stan
%
% Requires CmdStan on PATH (Trinity preferences) and intertemporalChoice data.
% Chains: stan/storage/{modelName}_intertemporalChoice_stan.mat
% Figures: stan/figures/

clear;
close all;

cd(fileparts(mfilename('fullpath')));

executionScripts = { ...
  'exponentialExecutionHierarchicalStan', ...
  'hyperbolicExecutionHierarchicalStan', ...
  'hyperboloidExecutionHierarchicalStan', ...
  'proportionalDifferencesExecutionHierarchicalStan', ...
  'directDifferencesExecutionHierarchicalStan', ...
  'tradeoffExecutionHierarchicalStan', ...
  'unifiedTradeoffExecutionHierarchicalStan', ...
  'itchExecutionHierarchicalStan'};

probitScripts = { ...
  'exponentialHierarchicalStan', ...
  'hyperbolicHierarchicalStan', ...
  'hyperboloidHierarchicalStan', ...
  'proportionalDifferencesHierarchicalStan', ...
  'directDifferencesHierarchicalStan', ...
  'tradeoffHierarchicalStan', ...
  'unifiedTradeoffHierarchicalStan', ...
  'itchHierarchicalStan'};

scriptGroups = {executionScripts, probitScripts};
groupLabels = {'execution (epsilon)', 'probit (sigma)'};

for g = 1:numel(scriptGroups)
  fprintf('\n######## hierarchical Stan %s models ########\n', groupLabels{g});
  scripts = scriptGroups{g};
  for k = 1:numel(scripts)
    fprintf('\n======== %s ========\n', scripts{k});
    run(scripts{k});
  end
end
