model in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/unifiedTradeoffExecutionHierarchicalMuPrecDouble_entrop/unifiedTradeoffExecutionHierarchicalMuPrecDouble_entrop_jags.jags"
data in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/unifiedTradeoffExecutionHierarchicalMuPrecDouble_entrop/unifiedTradeoffExecutionHierarchicalMuPrecDouble_entrop.data"
compile, nchains(1)
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/unifiedTradeoffExecutionHierarchicalMuPrecDouble_entrop/unifiedTradeoffExecutionHierarchicalMuPrecDouble_entrop_1.init"
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/unifiedTradeoffExecutionHierarchicalMuPrecDouble_entrop/unifiedTradeoffExecutionHierarchicalMuPrecDouble_entrop_1.seed"
initialize
update 1000
monitor set gamma, thin(8)
monitor set tau, thin(8)
monitor set kappa, thin(8)
monitor set vartheta, thin(8)
monitor set eta, thin(8)
monitor set w, thin(8)
update 16000
coda *, stem('samples_1_')
