model in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/exponentialExecutionHierarchicalMuPrecHalf_entrop/exponentialExecutionHierarchicalMuPrecHalf_entrop_jags.jags"
data in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/exponentialExecutionHierarchicalMuPrecHalf_entrop/exponentialExecutionHierarchicalMuPrecHalf_entrop.data"
compile, nchains(1)
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/exponentialExecutionHierarchicalMuPrecHalf_entrop/exponentialExecutionHierarchicalMuPrecHalf_entrop_5.init"
parameters in "/home/mdlee/Dropbox/GitHub/intertemporalChoice/models/tmp/exponentialExecutionHierarchicalMuPrecHalf_entrop/exponentialExecutionHierarchicalMuPrecHalf_entrop_5.seed"
initialize
update 2000
monitor set kappa, thin(1)
monitor set w, thin(1)
update 5000
coda *, stem('samples_5_')
